.\" Manpage for hyprland config.
.\" Contact zeioth@hotmail.com to correct errors or typos.
.TH man 8 "16 nov 2022" "1.0" "Hyprland config"
.SH NAME
Zeioth's personal hyprland congfiguration

.SH SYNOPSIS
 An Hyprland config you can \fBcopy into ~/.config/hypr\fP.
.SH DESCRIPTION
 Files and directories:
 \fBconfig\fP    Entry point file. Includes the other configs.
 \fBautostart.d\fP  Programs to run on startup.
 \fBvariables.d\fP  Commands we use in the configs.
 \fBconfig.d\fP   Hyprland settings.
 \fBhardware.d\fP hardware settings.
 \fBmodes.d\fP    keyboard modes.
 \fBscripted-features\fP    Optional things \fBcopy into ~/.local/bin\fP.
.SH EXAMPLES
 \fB1)\fP Add a variable to the file you choose on   \fB→ ./variables.d\fP
 \fB2)\fP Call it from a configuration you choose in \fB→ ./config.d\fP
 \fB3)\fP You can also call modes from               \fB→ ./config.d/keybindings \fP
.SH BUGS
 \fB-\fP Ranger 'terminal' command does not spawn in the current directory as it should.
.SH SEE ALSO
 \fB-\fP https://github.com/hyprwm/Hyprland
.SH AUTHOR
Adrian Lopez (zeioth@hotmail.com)
.SH COPYRIGHT
GPL - GNU General public license
